### ISSUE TITLE
NPCs with SP shouldn't take double SP damage

### ISSUE THREAD

**Issue by aniki21** [Stexinator/salvage-union-combat-automation#1]
NPCs can have HP or SP, so you might need an adjustment to the `applyDamageToHp` method to check whether the `healthType` property is `sp`.

https://github.com/Stexinator/salvage-union-combat-automation/blob/972b422e8ddfcd01a74f278056e68d4151fa7d61/src/scripts/damage.js#L38

```js
if(damage.includes("SP") && target.system.healthType !== 'sp') {
  damageNumber = damageNumber*2;
}
```

**Comment by Stexinator** [comment]
Fixed in https://github.com/Stexinator/salvage-union-combat-automation/releases/tag/v0.0.4
